### ISSUE TITLE
multiple formData issues

### ISSUE THREAD

**Issue by zboldyga** [RxNT/react-jsonschema-form-pagination#22]
I may be incorrectly pointing to the wrong project for the root of this issue. That said, I observed this while inserting sample formData into encounter playground and exploring the props and state of our various components.

1. When default formData is loaded, it seems that the pagination wrapper is not passing the formData into the pages where it is needed. Nothing displays in the rendered view, and nothing is in the props of the corresponding tab's form. I observed this with example initial data of { "height": "100" }.

2. When initial formData was provided, then a field in the form is manually adjusted, the initial formData was entirely overwritten in the pagination wrapper's state, despite changes to unrelated fields. The formData was also not propagated to the state of other wrappers. I'm unsure of what the value of submitted formData is in this case. 

3.  When data is manually entered into the form (regardless of whether there was initial formData), the state of the pagination wrapper's formData is updated properly, but it shows strange prop values (e.g. portions of what was typed in the field).

These are observations made using React's Chrome dev tools, using pagination version 0.1.14.

**Comment by mavarazy** [comment]
I've spread this issues in 3, so I can close them 
#23, #24 & #25

**Comment by mavarazy** [comment]
Addressed in appropriate issues
