### ISSUE TITLE
Adding "title" to the schema causes title to show on all tabs

### ISSUE THREAD

**Issue by andybarilla** [RxNT/react-jsonschema-form-pagination#26]
I added title to the playground schema: 

`const schema = {
  title: "test",
  type: "object",
  required: [],
  properties: {
    encounter: {
      type: "string",
      title: "Encounter",
    },
    firstName: {
      type: "string",
      title: "First name",
    },
    lastName: {
      type: "string",
      title: "Last name",
    },
    age: {
      type: "integer",
      title: "Age",
    },
    nickName: {
      type: "string",
      title: "nickname",
    },
    bio: {
      type: "string",
      title: "Bio",
    },
    password: {
      type: "string",
      title: "Password",
      minLength: 3,
    },
    telephone: {
      type: "string",
      title: "Telephone",
      minLength: 10,
    },
  },
};`

and the title shows on all the tabs as well as the top of the page:

![screenshot at 2017-09-08 09-54-40](https://user-images.githubusercontent.com/5983808/30220246-f0a24088-947b-11e7-88be-0499459270d8.png)

**Comment by andybarilla** [comment]
Note, the same issue occurs with "description"

**Comment by mavarazy** [comment]
@andybarilla thanks, I'll fix this.

**Comment by mavarazy** [comment]
@andybarilla I've fixed this and released a new version
