### ISSUE TITLE
styling wrapper in each tab

### ISSUE THREAD

**Issue by zboldyga** [RxNT/react-jsonschema-form-pagination#37]
In order to style the contents of each tab more flexibly, it would be great to have a single div that wraps all of the items that appear after the navigation menu, but that does not include the navigation menu itself.

Right now the navigation menu appears at the same level of the hierarchy as the form controls.

**Comment by mavarazy** [comment]
Current approach is to change original field representation with NavField and HiddenField, which allows to handle errors in a clearer way. So we can't simply add it, without complicating the rest of the pagination.
