### ISSUE TITLE
Calling 'setState()' in 'onChange()' breaks UX

### ISSUE THREAD

**Issue by adrian-swca** [RxNT/react-jsonschema-form-pagination#41]
When users attempt to input data into a form rendered w/ pagination, the data input breaks after performing a single action (i.e. a single keystroke, a single select) and the form resets itself to the first page.  The issue appears to be caused by [calling the setState method in the onChange method](https://github.com/RxNT/react-jsonschema-form-pagination/blob/f8fea4b7d3eb53c9dd27dc265164dbea0033e59d/playground/app/App.js#L21).

A current workaround is to replace this logic:
```
  handleChange = ({ formData }) => {
    this.setState({ formData });
  };
```

With this:
```
  handleChange = ({ formData }) => {
    Object.assign(this.state.formData, formData);
  };
```

**Comment by mavarazy** [comment]
@adrian-swca Can you provide a schema and uiSchema for this issue?
