### ISSUE TITLE
Why tabID is a String and not a number?

### ISSUE THREAD

**Issue by mavarazy** [RxNT/react-jsonschema-form-pagination#5]
I think it might result in less errors, if we use number as TAB identifier.

**Comment by zboldyga** [comment]
I was thinking I'd leave it open ended so we could use an actual ID here, as pulled from some schema management system. I can't think of a valid use case here though, and I see what you mean about the strings causing issues.

I'll revert to numbers.

**Comment by mavarazy** [comment]
This is no longer relevant, with the latest functionality.
